// curiosidades-el-burdel.js — Banco de curiosidades para "¿Sabías que?"
// ============================================================
// Contenido 100% local (no Firebase, no Gemini). Se selecciona una
// curiosidad por día usando el día del año, igual que "La frase de hoy"
// en frases.js — pero es un banco totalmente separado: acá van datos
// de cultura general (ciencia, animales, historia, geografía, etc.),
// no frases de la noche.
//
// Formato: array plano de strings.

export const CURIOSIDADES_EL_BURDEL = [

  "El pulpo tiene tres corazones: dos bombean sangre a las branquias y uno al resto del cuerpo.",
  "La miel no se pudre nunca: se encontraron potes de miel de más de 3000 años en tumbas egipcias, todavía comestibles.",
  "Las jirafas y los humanos tienen la misma cantidad de vértebras en el cuello: siete.",
  "Un rayo es unas cinco veces más caliente que la superficie del sol.",
  "El corazón de una ballena azul puede pesar tanto como un auto chico.",
  "Los pulpos tienen sangre azul, por el cobre que usan en vez de hierro para transportar oxígeno.",
  "La Torre Eiffel puede crecer hasta 15 cm en verano por la dilatación del metal con el calor.",
  "Las huellas dactilares de los koalas son tan parecidas a las humanas que podrían confundir una escena del crimen.",
  "Un grupo de flamencos se llama, literalmente, una \"flamboyance\".",
  "El sonido no viaja en el espacio porque no hay aire ni ningún medio para transmitirlo.",
  "Los elefantes son de los pocos animales que pueden reconocerse a sí mismos en un espejo.",
  "Venus es el planeta más caliente del sistema solar, más que Mercurio, por su atmósfera densa.",
  "Las vacas tienen mejores amigas: se estresan cuando las separan de otra vaca con la que se llevan bien.",
  "El ADN humano comparte cerca de un 60% de similitud con el de una banana.",
  "Un día en Venus dura más que un año en Venus: tarda más en girar sobre su eje que en dar la vuelta al sol.",
  "Los tiburones existen desde antes que los árboles: aparecieron hace unos 400 millones de años.",
  "El agua caliente puede congelarse más rápido que el agua fría en ciertas condiciones (se llama efecto Mpemba).",
  "Las nutrias marinas duermen tomadas de la mano para no separarse con la corriente.",
  "El cerebro humano consume cerca del 20% de la energía total del cuerpo, aunque pesa solo el 2%.",
  "En la Antigua Roma, la orina se usaba para lavar la ropa por el amoníaco que contiene.",
  "Los avestruces pueden correr más rápido que los caballos, hasta unos 70 km/h.",
  "Groenlandia es la isla más grande del mundo, pero tiene menos habitantes que muchas ciudades chicas.",
  "El corazón humano late más de 100.000 veces por día sin que lo pensemos.",
  "Las abejas pueden reconocer rostros humanos individuales.",
  "La Gran Muralla China no se ve a simple vista desde el espacio, al contrario del mito popular.",
  "Los caballitos de mar son los únicos animales en los que el macho queda embarazado y da a luz.",
  "El sol representa más del 99,8% de toda la masa del sistema solar.",
  "Las hormigas no tienen pulmones: respiran por unos agujeritos llamados espiráculos.",
  "Un rayo cae en algún lugar de la Tierra unas 8 millones de veces por día.",
  "Los delfines tienen nombres propios: usan un silbido único para identificarse entre ellos.",
  "El diamante y el grafito de un lápiz están hechos exactamente del mismo elemento: carbono.",
  "La lengua del camaleón puede ser más larga que su propio cuerpo.",
  "En Japón hay más mascotas que niños menores de 15 años.",
  "El Monte Everest crece unos pocos milímetros por año por el movimiento de las placas tectónicas.",
  "Los pingüinos emperador pueden aguantar la respiración bajo el agua hasta 20 minutos.",
  "La Coca-Cola se inventó originalmente como un remedio medicinal.",
  "El ojo humano puede distinguir alrededor de 10 millones de colores distintos.",
  "Las mariposas saborean con las patas, no con la boca.",
  "El primer email de la historia se envió en 1971, mucho antes de que existiera internet como la conocemos.",
  "Los pulpos pueden cambiar de color y de textura de piel en menos de un segundo.",
  "Finlandia tiene más de 180.000 lagos, casi uno por cada 30 habitantes.",
  "El corazón de un camarón mantis puede lanzar un golpe tan rápido que genera una pequeña burbuja de vapor.",
  "Los canguros no pueden caminar hacia atrás.",
  "La Antártida es técnicamente el desierto más grande del mundo, por lo poca lluvia que recibe.",
  "Un adulto promedio tiene entre 5 y 6 litros de sangre en el cuerpo.",
  "El chicle se inventó a partir de la resina de un árbol llamado chicozapote.",
  "Los búhos no pueden mover los ojos: por eso giran tanto la cabeza, hasta 270 grados.",
  "Las plantas de banana no son árboles: técnicamente son la hierba más grande del mundo.",
  "El primer animal clonado fue una oveja llamada Dolly, en 1996.",
  "Los castores pueden aguantar la respiración hasta 15 minutos bajo el agua.",
  "Islandia no tiene ejército propio desde hace más de 70 años.",
  "El corazón de una gamba está ubicado en su cabeza.",
  "Las cebras son negras con rayas blancas, no al revés: su piel de base es oscura.",
  "El agua cubre alrededor del 71% de la superficie de la Tierra.",
  "Los perros pueden oler emociones humanas a través de cambios en el sudor y la respiración.",
  "El primer video subido a YouTube se llamó \"Me at the zoo\" y dura apenas 19 segundos.",
  "La sandía está compuesta por más de un 90% de agua.",
  "Los caracoles pueden dormir hasta tres años seguidos en épocas de sequía.",
  "El Sahara, el desierto cálido más grande del mundo, alguna vez fue una zona verde y fértil.",
  "Las abejas necesitan visitar unas dos millones de flores para producir medio kilo de miel.",
  "El planeta Saturno es tan liviano en relación a su tamaño que flotaría en agua si existiera una bañera lo bastante grande.",
  "Los gatos pasan cerca de dos tercios de su vida durmiendo.",
  "La Torre Eiffel fue pensada como una estructura temporal para una exposición y casi la demuelen después.",
  "Los pulpos tienen nueve cerebros: uno central y uno en cada uno de sus ocho brazos.",
  "El sonido de una persona chasqueando los dedos viaja a la velocidad del sonido, unos 343 metros por segundo.",
  "Las hienas se ríen como forma de comunicación social, no necesariamente por diversión.",
  "El río Amazonas transporta más agua que los siguientes siete ríos más grandes del mundo juntos.",
  "Los flamencos son rosados por los pigmentos de los camarones y algas que comen.",
  "El cerebro humano sigue desarrollándose hasta los 25 años aproximadamente.",
  "Un caracol puede dormir con hasta tres días de sueño continuo sin moverse.",
  "El primer país en dar el voto a las mujeres fue Nueva Zelanda, en 1893.",
  "Los elefantes son los únicos animales que no pueden saltar.",
  "El chocolate negro contiene compuestos que pueden mejorar levemente el estado de ánimo.",
  "El planeta Marte tiene el volcán más grande del sistema solar conocido: el Monte Olimpo.",
  "Las arañas no son insectos: son arácnidos, con ocho patas en vez de seis.",
  "El agua del mar Muerto tiene tanta sal que es casi imposible hundirse en ella.",
  "Los tiburones ballena son el pez más grande del mundo y se alimentan solo de plancton.",
  "La miel es el único alimento que técnicamente nunca caduca si se conserva bien sellada.",
  "El corazón de un colibrí puede latir más de 1000 veces por minuto en pleno vuelo.",
  "Rusia es tan grande que abarca once husos horarios distintos.",
  "Las tortugas pueden respirar por la zona cercana a la cola en algunas especies acuáticas.",
  "El primer disco rígido de computadora, en 1956, pesaba más de una tonelada y guardaba apenas 5 megabytes.",
  "Los caballos pueden dormir de pie gracias a un mecanismo de bloqueo en sus patas.",
  "El desierto de Atacama, en Chile, es uno de los lugares más secos del planeta.",
  "Las lombrices de tierra tienen cinco pares de corazones.",
  "El planeta Júpiter tiene una tormenta, la Gran Mancha Roja, que dura activa desde hace más de 300 años.",
  "Los pulpos pueden abrir frascos con tapa a rosca para llegar a su comida.",
  "El sonido de un estornudo puede viajar a más de 150 km/h.",
  "Canadá tiene más lagos que el resto de los países del mundo juntos.",
  "Las mariposas monarca migran miles de kilómetros cada año, de Norteamérica a México.",
  "El corazón humano tiene el tamaño aproximado de un puño cerrado.",
  "Los camellos almacenan grasa en la joroba, no agua, como se cree popularmente.",
  "El primer mensaje de texto (SMS) se envió en 1992 y decía simplemente \"Feliz Navidad\".",
  "Las abejas pueden reconocer patrones matemáticos simples, como el concepto de cero.",
  "El planeta Neptuno tiene vientos que pueden superar los 2000 km/h, los más fuertes del sistema solar.",
  "Los gatos no pueden saborear lo dulce: les falta el receptor específico para eso.",
  "La Gran Barrera de Coral, en Australia, es la estructura viva más grande del mundo.",
  "El cerebro humano no siente dolor directamente, aunque procese todo el dolor del cuerpo.",
  "Las hormigas pueden cargar hasta 50 veces su propio peso corporal.",
  "El primer semáforo del mundo se instaló en Londres en 1868 y funcionaba a gas.",
  "Los pingüinos pueden saltar hasta dos metros de altura fuera del agua.",
  "El punto más profundo del océano, la Fosa de las Marianas, supera los 10.000 metros de profundidad.",
  "Las jirafas duermen muy poco: entre 30 minutos y 2 horas por día.",
  "El primer videojuego reconocido, \"Tennis for Two\", se creó en 1958 en un osciloscopio.",
  "Los koalas duermen entre 18 y 22 horas por día, entre las más largas del reino animal.",
  "El planeta Mercurio no tiene atmósfera real, por lo que sus temperaturas varían muchísimo entre el día y la noche.",
  "Las nutrias usan piedras como herramientas para romper caparazones de moluscos.",
  "El corazón de una jirafa puede pesar hasta 11 kilos por lo que tiene que bombear sangre tan alto.",
  "Los caracoles tienen entre 14.000 y 25.000 dientes microscópicos en la lengua.",
  "El primer puente colgante moderno se construyó en el siglo XIX y revolucionó la ingeniería civil.",
  "Las ballenas jorobadas cantan canciones que pueden durar hasta 30 minutos y cambian con el tiempo.",
  "El planeta Tierra es el único conocido con placas tectónicas activas del sistema solar.",
  "Los pulpos pueden regenerar un brazo perdido por completo en pocos meses.",
  "El primer zoológico público del mundo abrió en Viena en 1752 y todavía funciona.",
  "Las abejas reina pueden vivir varios años, mientras que las obreras solo viven unas semanas.",
  "El Sahara puede recibir nieve ocasionalmente en algunas zonas elevadas, aunque sea raro.",
  "Los rinocerontes se comunican entre sí a través de sus excrementos, que funcionan casi como un cartel informativo.",
  "El planeta Urano gira prácticamente de costado respecto al resto del sistema solar.",
  "Las libélulas pueden volar en las seis direcciones: adelante, atrás, arriba, abajo y a los costados.",
  "El primer mapa impreso del mundo se hizo en el año 1507 y ya incluía el nombre \"América\".",
  "Los pulpos tienen un sistema nervioso tan distribuido que cada brazo puede \"pensar\" de forma casi independiente.",
  "Las abejas baten sus alas unas 200 veces por segundo, lo que genera el característico zumbido.",
  "El desierto del Sahara es casi del mismo tamaño que todo el territorio de Estados Unidos.",
  "Los pulpos y los calamares pueden expulsar tinta para escapar de los depredadores.",
  "El primer robot industrial se instaló en una fábrica de autos en 1961.",
  "Las abejas melíferas pueden reconocer y recordar el rostro de un apicultor con el tiempo.",
  "El planeta Plutón, hoy clasificado como planeta enano, tiene una luna, Caronte, casi la mitad de su tamaño.",
  "Los elefantes pueden detectar vibraciones del suelo a través de las patas para \"escuchar\" a otros elefantes lejanos.",
  "La primera fotografía permanente de la historia se tomó en 1826 y necesitó unas 8 horas de exposición.",
  "Los tiburones no tienen huesos: su esqueleto está hecho de cartílago.",
  "El corazón de una araña bombea sangre por todo su cuerpo sin necesidad de vasos sanguíneos cerrados.",
  "Las auroras boreales se producen por partículas solares que chocan contra la atmósfera terrestre.",
  "Los caballos pueden identificar expresiones faciales humanas de enojo o alegría.",

];

// ── Selección determinística por día del año ──
// Mismo mecanismo que getFraseDelDia en frases.js, pero es un banco
// totalmente independiente: "¿Sabías que?" y "La frase de hoy" nunca
// comparten fuente de datos.

export function getCuriosidadDelDia(date = new Date()) {
  const inicioDeAno = new Date(date.getFullYear(), 0, 0);
  const diffMs = date - inicioDeAno;
  const diaDelAno = Math.floor(diffMs / (1000 * 60 * 60 * 24)); // 1..365/366
  const index = (diaDelAno - 1) % CURIOSIDADES_EL_BURDEL.length;
  return CURIOSIDADES_EL_BURDEL[index];
}
