// frases-el-burdel.js — Banco de 365 frases para "La frase de hoy"
// ============================================================
// Contenido 100% local (no Firebase). Se selecciona una frase por día
// usando el día del año (1-365/366), de forma que todos los visitantes
// vean la misma frase el mismo día y cambie sola a la medianoche.
//
// Formato: array plano de strings, sin categorías en el código
// (las categorías de abajo son solo para que sea más fácil editarlas).

export const FRASES_EL_BURDEL = [

  // ── NOCHE (1-55) ──
  "La noche no pregunta, solo cobra.",
  "A las 3 AM todos somos filósofos de bar.",
  "El Burdel no cierra, vos te vas.",
  "Acá el WhatsApp del día siguiente se escribe solo.",
  "La noche empieza cuando alguien dice \"una última y nos vamos\".",
  "Nadie entra a El Burdel por accidente.",
  "El after de tu after.",
  "A esta hora ya no hay excusas, hay anécdotas.",
  "La noche siempre gana, vos solo participás.",
  "Acá el reloj es decorativo.",
  "Mañana vas a mentir sobre cuántas jugaste.",
  "El Burdel no tiene horario de cierre, tiene sobrevivientes.",
  "La luz del día es solo un rumor lejano.",
  "A las 2 AM las malas decisiones se sienten geniales.",
  "Esta noche no se explica, se vive.",
  "El que se va temprano, después pregunta qué pasó.",
  "La noche tiene memoria selectiva, por suerte.",
  "Acá adentro no existe el \"mañana trabajo\".",
  "El Burdel te encuentra, vos no lo buscás.",
  "Nadie sale igual de cómo entró.",
  "La noche te debe una explicación, no te la va a dar.",
  "A esta hora todos tienen una teoría sobre todo.",
  "El Burdel no perdona el \"me voy en 5 minutos\".",
  "Cuanto más tarde es, más sentido tiene todo.",
  "La noche es la única que no miente sobre lo que pasó.",
  "Acá el \"quedate un rato más\" es ley.",
  "El Burdel no tiene salida de emergencia, tiene otra ronda.",
  "A las 4 AM ya nadie recuerda quién propuso qué juego.",
  "La noche siempre deja tarea para el grupo de WhatsApp.",
  "El que dijo \"vengo por una hora\" ya perdió.",
  "Esta noche va a tener una segunda parte que nadie va a contar bien.",
  "El Burdel no se cuenta, se sobrevive.",
  "La noche no perdona a los que miran el celular.",
  "A esta hora las excusas ya no convencen a nadie.",
  "El Burdel es el único lugar donde \"ya fue\" tiene sentido.",
  "La madrugada es la hora oficial de las malas ideas geniales.",
  "Nadie se acuerda cómo empezó, todos recuerdan cómo terminó.",
  "El Burdel no tiene fin de fiesta, tiene pausas.",
  "A esta hora todo chiste es mejor de lo que es.",
  "La noche te va a preguntar si valió la pena. Va a valer.",
  "El Burdel no cierra la puerta, la deja entornada.",
  "Acá \"ya nos vamos\" es sinónimo de \"faltan dos horas\".",
  "La noche no tiene testigos confiables.",
  "El Burdel convierte lunes en anécdotas de viernes.",
  "A las 5 AM ya sos otra persona, para bien o para mal.",
  "La noche no se negocia, se acepta.",
  "El Burdel siempre tiene una luz prendida para el que llega tarde.",
  "Acá el bostezo es una mentira que nadie se cree.",
  "La noche te suelta cuando ella quiere, no cuando vos querés.",
  "El Burdel no tiene última partida, tiene \"una más\".",
  "A esta hora todos son expertos en todo.",
  "La noche no repite función, cada una es única.",
  "El Burdel te devuelve distinto de como te recibió.",
  "Acá \"me quedo 10 minutos más\" ya es una tradición.",
  "La noche no se acaba, se pausa hasta la próxima.",

  // ── JUEGOS (56-110) ──
  "En Taboo, el silencio te delata más que la palabra prohibida.",
  "Wordle no perdona la primera letra apurada.",
  "El Impostor más peligroso es el que jura que no sabe mentir.",
  "En ¿Quién Soy? todos hacen la misma pregunta primero, y a nadie le sirve.",
  "La Ruleta no tiene favoritos, solo tiene suerte esa noche.",
  "El Millonario siempre está más cerca de lo que parece.",
  "Nadie gana a Taboo sin traicionar a alguien con la mirada.",
  "Wordle en 6 letras separa a los genios de los que improvisan.",
  "El mejor Impostor es el que vota primero para despistar.",
  "En ¿Quién Soy? el que se ríe solo, ya perdió.",
  "La Ruleta castiga a los que apuestan por orgullo.",
  "El Millonario no confía en nadie, y hace bien.",
  "En Taboo, \"es como\" siempre termina en descalificación.",
  "Wordle te hace sentir Einstein y estúpido en el mismo minuto.",
  "El Impostor bueno no defiende, ataca primero.",
  "En ¿Quién Soy? preguntar \"¿estoy vivo?\" ya es sospechoso.",
  "La Ruleta no entiende de estrategias, solo de nervios.",
  "El Millonario más peligroso es el que parece no jugar.",
  "En Taboo, el gesto con las manos siempre te condena.",
  "Wordle: la palabra del día siempre sabe más que vos.",
  "El Impostor gana cuando todos dudan de la persona correcta.",
  "¿Quién Soy? te obliga a hacer preguntas que dan vergüenza ajena.",
  "La Ruleta separa a los valientes de los que fingen que no les importa.",
  "El Millonario premia al que sabe cuándo callarse.",
  "En Taboo hay más traiciones que en cualquier otro juego de la noche.",
  "Wordle a las 3 AM es un deporte de riesgo.",
  "El Impostor perfecto es el que ya ganó antes de empezar a hablar.",
  "En ¿Quién Soy? el peor personaje siempre te toca a vos.",
  "La Ruleta no da revancha, da otra vuelta.",
  "El Millonario esconde mejor sus cartas que sus intenciones.",
  "En Taboo, decir \"rima con\" es rendirse.",
  "Wordle: si la primera palabra no funciona, ya arruinaste la noche.",
  "El Impostor más obvio nunca es el impostor.",
  "¿Quién Soy? te hace dudar hasta de tu propia identidad.",
  "La Ruleta gira, la culpa también.",
  "El Millonario que grita \"confío en vos\" ya te está por traicionar.",
  "En Taboo, el equipo que pierde siempre acusa al mazo.",
  "Wordle te da 6 intentos y una crisis existencial.",
  "El Impostor te enseña que confiar es el verdadero juego.",
  "En ¿Quién Soy? nadie adivina rápido, todos fingen que sí.",
  "La Ruleta es la única sincera de la noche: no le importa nadie.",
  "El Millonario recuerda cada traición, aunque diga que no.",
  "En Taboo, \"no puedo decir eso\" es la frase más usada de la noche.",
  "Wordle: la palabra correcta siempre aparece un segundo tarde.",
  "El Impostor bueno se victimiza primero, ataca después.",
  "¿Quién Soy? convierte preguntas inocentes en interrogatorios.",
  "La Ruleta no perdona a los indecisos.",
  "El Millonario más rico de la noche es el que menos habló.",
  "En Taboo, el equipo azul siempre jura que jugó mejor.",
  "Wordle es el único juego donde perder también se comparte con orgullo.",
  "El Impostor sabe que la mejor mentira empieza con la verdad.",
  "En ¿Quién Soy? el personaje más difícil siempre es \"uno mismo\".",
  "La Ruleta no tiene amigos, tiene números.",
  "El Millonario gana silencio, no discusiones.",
  "Nadie sale de una partida de Impostor confiando en el mismo amigo de antes.",

  // ── AMISTAD (111-160) ──
  "Tus amigos no te bancan, te toleran con estilo.",
  "El grupo de WhatsApp de El Burdel nunca duerme.",
  "La amistad real se mide en cuántas veces te cubrieron una mentira.",
  "Un buen amigo miente por vos en el momento justo.",
  "Acá el \"te juro que fue así\" no convence a nadie, pero se acepta.",
  "La lealtad se prueba cuando alguien pregunta \"¿quién empezó?\".",
  "Tus amigos son los únicos que se ríen de tu desgracia con cariño.",
  "El Burdel te da amigos que después se convierten en cómplices.",
  "Nadie elige a sus amigos, los hereda una noche de estas.",
  "La confianza se rompe fácil, pero acá se reconstruye con una ronda más.",
  "Un buen grupo de amigos nunca te deja jugar solo al Impostor.",
  "Tus amigos van a recordar el error para siempre, con cariño y sin piedad.",
  "La amistad de verdad aguanta hasta el chiste que no tiene gracia.",
  "Acá los amigos no te dejan solo, te dejan en ridículo acompañado.",
  "El mejor amigo es el que graba el momento vergonzoso \"para el recuerdo\".",
  "Nadie te conoce tanto como el que jugó Taboo con vos y perdió la paciencia.",
  "Los verdaderos amigos comparten la culpa, no la asumen.",
  "En El Burdel los enemigos también terminan siendo del grupo.",
  "La amistad se mide en memes que nadie más entiende.",
  "Tus amigos no te van a salvar, te van a acompañar en la caída.",
  "El que te defiende en el Impostor, te traiciona en la Ruleta.",
  "Acá \"somos familia\" se dice después de la tercera partida.",
  "Un buen amigo te avisa cuando estás por decir una boludez, después de que la dijiste.",
  "La amistad real empieza cuando alguien admite que hizo trampa.",
  "Nadie se hace amigo en El Burdel por casualidad, se hace por resistencia.",
  "Tus amigos son los únicos autorizados a burlarse de tu voz de Impostor.",
  "La lealtad tiene límites, y esos límites se llaman \"quién vota a quién\".",
  "El grupo que juega junto, se traiciona junto.",
  "Un amigo de verdad te presta el celular para hacer trampa, y después lo niega.",
  "Acá los mejores amigos son los peores compañeros de equipo.",
  "La amistad se fortalece con cada ronda perdida injustamente.",
  "Nadie olvida al amigo que reveló el secreto en el peor momento.",
  "Nadie se salva solo, algunos se salvan riéndose del que no se salvó.",
  "El Burdel te enseña quién te banca de verdad y quién solo mira.",
  "Un buen amigo se ríe con vos. Uno mejor, se ríe de vos también.",
  "La amistad sobrevive a las peores excusas para no pagar la ronda.",
  "Acá \"no te enojes\" siempre llega tarde.",
  "Nadie te va a dejar mentir solo, te acompañan en el relato.",
  "La confianza ciega en un amigo termina siendo el mejor chiste de la noche.",
  "El Burdel junta gente random y los convierte en cómplices para siempre.",
  "Tus amigos son los que te bancan la vergüenza y la reparten en el grupo.",
  "La amistad real no perdona, pero acompaña.",
  "Un amigo te avisa la palabra prohibida por debajo de la mesa.",
  "Nadie se hace tan amigo como el que perdió contra vos en Wordle.",
  "Acá los rencores duran hasta la próxima ronda, después se olvidan.",
  "La lealtad tiene un precio: una ficha, un trago, o una mentira compartida.",
  "El mejor amigo es el que reparte la culpa equitativamente.",
  "Acá \"somos un equipo\" dura hasta que alguien vota mal.",
  "La amistad de El Burdel se construye a las risas y se derrumba a los votos.",
  "Nadie te va a cuidar tanto como el amigo que quiere ganarte al mismo juego.",

  // ── ABSURDO (161-215) ──
  "El impostor de tu vida probablemente sos vos.",
  "Las cabras también tienen favoritos, y no sos vos.",
  "En algún lugar, alguien está perdiendo al Wordle ahora mismo. Puede que seas vos.",
  "El silencio incómodo también cuenta puntos.",
  "Nadie sabe por qué el mazo de Taboo siempre te odia a vos primero.",
  "La suerte no existe, pero la Ruleta hace como que sí.",
  "Todos los grupos de amigos tienen un impostor que nunca fue descubierto.",
  "El universo conspira, pero solo en Wordle.",
  "Hay una teoría de que el que gana siempre hizo trampa. Es correcta.",
  "La lógica no aplica después de la medianoche.",
  "Alguien, en algún lado, está a punto de decir la palabra prohibida sin saberlo.",
  "El destino se decide con una ruleta y mucha negación.",
  "En El Burdel, hasta el silencio tiene estrategia.",
  "Los números de la Ruleta se ríen de vos en privado.",
  "Nadie explicó nunca por qué el que más habla, menos gana.",
  "La estadística dice que vas a perder. La esperanza dice lo contrario. Ganó la estadística.",
  "Todo empieza con \"dale, una rapidita\" y termina en las 4 AM.",
  "El caos tiene reglas, solo que nadie las escribió.",
  "Alguna vez alguien ganó El Millonario sin saber que estaba jugando.",
  "La probabilidad de que digas la palabra prohibida aumenta con el nerviosismo.",
  "El Burdel tiene una física propia donde el tiempo no aplica.",
  "Nadie sabe cómo terminó esa ronda, pero todos tienen una versión distinta.",
  "En algún multiverso, ganaste todas las partidas de esta noche.",
  "La suerte de la Ruleta se hereda, no se gana.",
  "El impostor perfecto también duda de sí mismo a veces.",
  "Un dato random: el 100% de las excusas de \"me quedo 5 minutos\" son mentira.",
  "Nadie explicó por qué las mejores ideas surgen a las 3 AM y desaparecen a la mañana.",
  "La teoría del caos se probó por primera vez en una partida de Impostor.",
  "El multiverso también tiene su propio grupo de El Burdel, y ahí perdés igual.",
  "Las palabras prohibidas de Taboo tienen memoria y te van a esperar otro día.",
  "En algún lado del planeta, alguien está discutiendo si ganó por trampa o por suerte.",
  "La Ruleta no entiende de karma, pero actúa como si supiera algo.",
  "Nadie sabe qué pasaría si jugaran todos los juegos de El Burdel al mismo tiempo. Sería el fin.",
  "El impostor de la noche también es impostor en su propia vida, probablemente.",
  "Hay una versión de vos en otro universo que sí ganó el Wordle en dos intentos.",
  "Las reglas de El Burdel cambian según cuánto se tomó.",
  "Nadie puede explicar por qué siempre falta una ficha de la Ruleta.",
  "El azar y la mala suerte son primos hermanos en esta casa.",
  "Un estudio no oficial confirma: los que más gritan \"yo no fui\", fueron.",
  "En algún momento de la noche, todos se convierten en expertos de todo sin saber nada.",
  "La teoría de que \"el que reparte, gana\" nunca se pudo comprobar del todo.",
  "Alguien en esta sala está pensando en la palabra prohibida ahora mismo.",
  "El Burdel no tiene reglas físicas, tiene reglas de conveniencia.",
  "Nadie sabe por qué las 2 AM siempre parecen las 11 PM.",
  "La lógica del Impostor dice: cuanto más inocente parecés, más sospechoso sos.",
  "Existe una posibilidad, remota pero real, de que el Millonario seas vos sin saberlo.",
  "El karma en El Burdel se paga en la próxima ronda, no después.",
  "Nadie entiende por qué siempre hay una ficha de más o de menos.",
  "La ciencia todavía no explica por qué reímos más fuerte cuando perdemos.",
  "En El Burdel, hasta la mala suerte tiene su club de fans.",
  "El multiverso tiene infinitas versiones de esta noche, y en todas perdiste el Wordle igual.",
  "Nadie puede probar que el Impostor ganó limpio, pero tampoco lo pueden acusar.",
  "La teoría del \"yo no hice nada\" se desmiente sola, siempre.",
  "Alguna vez, en algún lugar, alguien ganó todo sin darse cuenta de cómo.",
  "El azar de la Ruleta tiene favoritos, y esos favoritos no sos vos.",

  // ── DOBLE SENTIDO (216-260) ──
  "En El Burdel, el que la sigue, la consigue. O al menos gana la próxima ronda.",
  "Dicen que en la noche todo entra. Menos la palabra prohibida en Taboo.",
  "Acá \"una más\" nunca es solo una.",
  "Lo que pasa en la ronda, se queda en la ronda. Menos las fotos.",
  "En El Burdel, meterse en problemas es parte del juego.",
  "Nadie sale de acá sin al menos un secreto que guardar.",
  "La tensión en la mesa de Impostor se corta con cuchillo, o con otra ronda.",
  "Acá todo el mundo quiere ganar, pero nadie quiere admitir cuánto.",
  "En la Ruleta, girar rápido no siempre te conviene.",
  "El que aguanta más tiempo despierto, gana más de lo que cree.",
  "En El Burdel, meter mano en el mazo tiene consecuencias.",
  "Todos dicen que vienen \"solo a mirar\", y después son los últimos en irse.",
  "La noche se pone interesante cuando alguien deja de fingir que no le importa.",
  "Acá \"quedate un rato más\" tiene doble filo y todos lo saben.",
  "Nadie entra al Burdel inocente, pero todos salen distintos.",
  "El juego se pone bueno cuando alguien empieza a jugar sucio.",
  "En Taboo, decir de más siempre tiene su precio.",
  "La química en la mesa se nota más después de la segunda ronda.",
  "Acá el que reparte cartas, controla mucho más que el juego.",
  "Todos quieren ganar rápido, pero los mejores juegos se disfrutan lento.",
  "En la Ruleta, apostar fuerte tiene su recompensa, o su castigo.",
  "Nadie se va de acá sin haber cruzado al menos una línea.",
  "El Burdel premia a los que se animan a jugar sin vergüenza.",
  "Acá \"vení, te explico las reglas\" nunca es solo sobre el juego.",
  "La mejor jugada de la noche no siempre está en el tablero.",
  "En Impostor, mentir bien tiene su encanto, hay que admitirlo.",
  "Todos entran buscando ganar algo, pocos admiten qué.",
  "La noche recompensa a los que se sueltan un poco más de lo normal.",
  "En El Burdel, perder también puede salir bien parado.",
  "Acá el \"dale, un juego más\" siempre esconde otra intención.",
  "Nadie sale ileso de una buena partida bien jugada.",
  "La mesa se calienta más rápido de lo que el juego indica.",
  "En Wordle, acertar a la primera te hace sentir invencible, y se nota.",
  "Todos quieren el premio, pocos preguntan qué hay que hacer para ganarlo.",
  "Acá jugar en equipo tiene sus ventajas, y sus roces.",
  "La complicidad se construye rápido cuando hay una mesa de por medio.",
  "En El Burdel, el que juega para ganar, siempre juega distinto.",
  "Nadie te va a juzgar por lo que hiciste para ganar esta ronda.",
  "Acá \"confiá en mí\" es la frase más usada y la menos cumplida.",
  "La tensión de la última ronda se siente en todo el cuerpo.",
  "En El Burdel, hasta perder puede dejarte con ganas de más.",
  "Todos dicen que vienen a jugar limpio, y ninguno lo cumple del todo.",
  "La química del grupo mejora considerablemente después de la tercera ronda.",
  "En El Burdel, animarse tiene su recompensa, siempre.",
  "Nadie termina la noche exactamente como la empezó, y está bien así.",

  // ── POLÉMICA (261-310) ──
  "La piña en la pizza no es el problema, el que la defiende sí.",
  "El asado a término medio genera más discusiones que cualquier elección.",
  "Poner ketchup al asado debería ser motivo de descalificación grupal.",
  "El que dice \"no soy celoso/a\" en El Burdel, generalmente lo es.",
  "La discusión sobre quién arruinó la última ronda nunca tiene ganador.",
  "El mate lavado es una falta de respeto disfrazada de amabilidad.",
  "Decir \"yo no tomo tanto\" a las 2 AM ya es sospechoso.",
  "El verdadero drama de la noche siempre es sobre quién tenía razón en un dato random.",
  "El helado de dulce de leche granizado no es superior, es solo el más gritón.",
  "Discutir de fútbol en El Burdel termina peor que cualquier ronda de Impostor.",
  "El que llega tarde y pregunta las reglas ya perdió el respeto del grupo.",
  "La birra caliente es un crimen que nadie quiere denunciar en voz alta.",
  "El curry en la milanesa divide más que cualquier elección presidencial.",
  "Decir \"el anterior estaba mejor\" del grupo de amigos es una declaración de guerra.",
  "El que corta la pizza en cuadrados en vez de triángulos no es de fiar.",
  "La discusión de quién manejó peor esa vez nunca se resuelve del todo.",
  "El que defiende la piña en la pizza también hace trampa en la Ruleta, coincidencia.",
  "Decir que el Fernet con Coca es \"medio así nomás\" te saca del grupo.",
  "El verdadero impostor de la noche es el que dice que no le gusta el asado.",
  "Nadie se pone de acuerdo sobre a qué hora es realmente \"temprano\" para irse.",
  "El que prende la luz antes de que termine la ronda merece juicio popular.",
  "Discutir sobre el mejor equipo de la noche siempre termina en empate técnico y bronca.",
  "El que dice \"una más y nos vamos\" ya perdió toda credibilidad para siempre.",
  "La discusión sobre quién invitó a quién esa noche nunca tiene una versión oficial.",
  "El que toma Coca Zero en El Burdel genera más preguntas que respuestas.",
  "Decir que el Wordle es \"fácil\" es la frase más polémica de la noche.",
  "El verdadero drama no es el juego, es quién eligió la música.",
  "Nadie se pone de acuerdo en si hacer trampa en Taboo es una habilidad o un pecado.",
  "El que defiende a un Impostor evidente merece ser investigado también.",
  "Decir \"yo juego mejor sobrio\" es la mentira más repetida del lugar.",
  "El asado sin chorizo genera más quejas que cualquier derrota en la Ruleta.",
  "El que pide \"bajale el volumen\" a las 3 AM está en el lugar equivocado.",
  "La discusión de quién rompió el silencio primero nunca se termina de resolver.",
  "Decir que \"no importa ganar\" es lo que dice siempre el que va perdiendo.",
  "El verdadero polémico de la noche es el que vota distinto a lo que dijo antes.",
  "Nadie se pone de acuerdo sobre si la Ruleta tiene trampa o mala suerte nomás.",
  "El que corta la conversación para revisar el celular ya rompió una regla no escrita.",
  "Discutir sobre quién tiene la mejor selfie de la noche siempre termina mal.",
  "El que dice \"esa palabra no cuenta\" en Taboo busca pelea directamente.",
  "La verdadera grieta de El Burdel es entre los que llegan temprano y los que llegan bien tarde.",
  "El que defiende una mentira obvia en Impostor no está jugando, está actuando mal.",
  "Decir \"yo no hago trampa\" mientras mirás la mano ajena es la polémica del año.",
  "Nadie se pone de acuerdo sobre si ganar sin querer cuenta como ganar de verdad.",
  "El verdadero debate de la noche es si el Millonario juega sucio o juega inteligente.",
  "Discutir sobre a quién le tocaba pagar la próxima ronda nunca termina bien.",
  "El que defiende quedarse \"solo un ratito más\" ya sabe que va a mentir.",
  "Decir que \"no pasa nada\" después de perder en Wordle es la frase más falsa de la noche.",
  "Nadie se pone de acuerdo si es peor hacer trampa o que te descubran.",
  "El verdadero enemigo público de la noche es el que apaga las luces antes de tiempo.",
  "Discutir quién tiene razón en El Burdel siempre termina en otra ronda, por las dudas.",

  // ── QUÉ CARAJO (311-365) ──
  "En algún momento de la noche, todos consideraron irse a vivir a otro país.",
  "Nadie sabe por qué, pero siempre hay uno que termina hablando de extraterrestres.",
  "El Burdel tiene una energía que hace que la gente confiese cosas random.",
  "A las 4 AM, alguien siempre propone algo que después nadie recuerda haber aceptado.",
  "Hay una posibilidad de que estemos todos actuando en la simulación de otro.",
  "El verdadero misterio de la noche es por qué siempre falta una silla.",
  "Nadie planea terminar hablando de la muerte a las 3 AM, pero pasa siempre.",
  "En algún momento vas a decir algo que no tiene sentido y todos lo van a aplaudir igual.",
  "El Burdel tiene el poder de convertir una charla normal en un debate filosófico sin aviso.",
  "A esta hora, cualquier teoría conspirativa suena razonable.",
  "Nadie sabe cómo terminamos hablando de esto, pero acá estamos.",
  "Hay una parte de la noche en la que todos se creen streamers sin cámara.",
  "El verdadero impostor podría ser el universo entero, pensalo.",
  "A las 3 AM, alguien va a preguntar \"¿y si en realidad todo esto es un sueño?\"",
  "Nadie sabe explicar por qué el grupo de amigos terminó discutiendo sobre dinosaurios.",
  "El Burdel convierte preguntas random en crisis existenciales compartidas.",
  "En algún momento de la noche, alguien va a decir \"esto lo tenemos que contar\" y nunca lo va a contar bien.",
  "Hay una teoría de que el que se ríe último, en realidad no entendió el chiste.",
  "Nadie sabe por qué siempre aparece un tema random que nadie pidió discutir.",
  "El verdadero caos de la noche empieza cuando alguien dice \"¿saben qué pensé?\"",
  "A esta hora, cualquier decisión se siente genial y terrible al mismo tiempo.",
  "Nadie planeó terminar la noche discutiendo sobre el sentido de la vida, pero bueno.",
  "El Burdel tiene una capacidad única de convertir un juego en una crisis de identidad.",
  "En algún momento, alguien va a jurar que \"esto ya pasó antes, exactamente igual\".",
  "Hay una posibilidad de que estemos repitiendo esta misma noche en loop.",
  "Nadie sabe por qué el grupo terminó hablando de teorías conspirativas a las 3 AM.",
  "El verdadero \"qué carajo\" de la noche llega siempre después de la tercera ronda.",
  "A esta hora, cualquier chiste malo se convierte en el mejor chiste del año.",
  "Nadie planeó que la noche terminara así, pero tampoco se sorprende nadie.",
  "El Burdel tiene el poder de hacerte cuestionar decisiones de hace 10 años.",
  "En algún momento vas a decir una frase random que se va a volver un chiste interno para siempre.",
  "Hay una teoría de que el impostor real siempre fue el anfitrión.",
  "Nadie sabe explicar cómo terminamos hablando de esto tan tarde.",
  "El verdadero misterio no es quién ganó, es cómo llegamos hasta acá.",
  "A las 4 AM, la lógica se toma la noche libre.",
  "Nadie planeó reírse tanto de algo que en realidad no daba tanta risa.",
  "El Burdel convierte cualquier silencio incómodo en una pregunta existencial.",
  "En algún momento de la noche vas a decir \"esto no se lo cuento a nadie\" y se lo vas a contar a todos.",
  "Hay una posibilidad de que el verdadero juego sea sobrevivir hasta el final de la noche.",
  "Nadie sabe por qué siempre hay uno que empieza a filosofar sin que nadie se lo pida.",
  "El verdadero \"qué carajo\" pasa cuando alguien recuerda algo que nadie más recuerda.",
  "A esta hora, cualquier teoría rara empieza a sonar con sentido común.",
  "Nadie planeó terminar discutiendo sobre el multiverso a esta hora, pero bueno, pasó.",
  "El Burdel tiene el don de hacer que una noche cualquiera se convierta en leyenda del grupo.",
  "En algún momento, alguien va a decir \"yo ya sabía\" sobre algo que obviamente no sabía.",
  "Hay una teoría de que las mejores noches empiezan mal y terminan siendo las mejores.",
  "Nadie sabe cómo pero siempre terminamos hablando de algo que no tiene nada que ver con el juego.",
  "El verdadero caos llega cuando alguien dice \"esperen, ¿y si hacemos esto?\"",
  "A esta hora, cualquier decisión mala se disfraza de decisión brillante.",
  "Nadie planeó que esta noche fuera memorable, y por eso lo es.",
  "El Burdel siempre deja una frase random dando vueltas en la cabeza de alguien al otro día.",
  "En algún momento, alguien va a preguntar la hora y se va a arrepentir de haberlo hecho.",
  "Hay una posibilidad real de que mañana nadie recuerde esta frase, y está perfecto así.",
  "El verdadero \"qué carajo\" de El Burdel es que siempre, siempre, hay una próxima vez.",
  "Nadie sale de El Burdel exactamente igual a como entró. Esa es la gracia.",

];

// ── Selección determinística por día del año ──
// Todos los visitantes ven la misma frase el mismo día, sin Firebase.
// Si el array tiene menos de 366 elementos, el 31/12 de un año bisiesto
// simplemente repite la frase del día anterior (no rompe nada, no hace falta el elemento 366).

export function getFraseDelDia(date = new Date()) {
  const inicioDeAno = new Date(date.getFullYear(), 0, 0);
  const diffMs = date - inicioDeAno;
  const diaDelAno = Math.floor(diffMs / (1000 * 60 * 60 * 24)); // 1..365/366
  const index = (diaDelAno - 1) % FRASES_EL_BURDEL.length;
  return FRASES_EL_BURDEL[index];
}

// "Frase de hoy" usa el mismo banco que "Sabías que", pero con un desfasaje
// de 180 días para que nunca coincidan el mismo día.
export function getFraseDelDiaOffset(offsetDias = 180, date = new Date()) {
  const desplazada = new Date(date.getTime() + offsetDias * 86400000);
  return getFraseDelDia(desplazada);
}
